version: '3.1'

services:
  prometheus:
    image: prom/prometheus
    user: 988:981
    volumes:
      - /opt/prometheus/etc:/etc/prometheus
      - /opt/prometheus/data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 9080:3000
    volumes:
      - /opt/prometheus/grafana:/var/lib/grafana
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=foobar'
      - 'GF_USERS_ALLOW_SIGN_UP=false'
    restart: unless-stopped
